### PR TITLE
new: [Chart options] POST or GET request with custom headers

### PR DESCRIPTION
**Pull request by mokaddem**
Hello,

As some API endpoints require to have specific headers like ``Authorization`` or use request headers to select their response format (CSV, JSON, ...), The following features has been implemented:
- Added possibility to choose between ``POST`` and ``GET`` request type
- Added possibility to set custom headers
- Added possibility to add a ``POST`` body (``POST`` request only)
- Support of the API preview

If you have comments or suggestions about the code, feel free to let me know.

Screenshot result:

image

### CODE REVIEW

**Comment by christabor** [comment]
Hey that's pretty cool. I think custom headers makes sense, but how did you expect authorization to work? If it's stored in the json config, it kind of defeats the purpose of secure authorization, as this is now plain-text and viewable by all with access to the dashboard. Barring that need, I don't see custom headers being used much - _maybe_ with something like `accept: application/json`, but returning json by default is so commonplace, especially for cases like these, it doesn't necessarily seem warranted.

As for POST, I think this violates the idea of the dashboarding tool - it is really only meant to be read-only. POST implicitly assumes some change in state, which doesn't seem appropriate.

This adds a lot of UI complexity for use-cases I'm not sure are valid, at least based on how I've used it or seen it used.

**Comment by mokaddem** [comment]
Hello,
Thank you for your feedback, it is much appreciated!
Let me justify this PR.

Indeed, authorization is stored in clear but it is much more convenient for the user this way as he don't need to set it again in case of a page reload.
Just to give a bit of context, I'm using ``flask_jsondash`` in a local environment (not exposed publicly) to show me some statistics from an API only accessible to admin. The access can only be granted if you are logged in or if you provide and API key (in the header) under the form of ``authorization``.
Even though, I don't see any other use for this feature, it could be handy for someone else.

Regarding POST, I added this option because it can be used to send query parameters (similar to GET queries). Even, if it is not the recommended way to fetch data, it adds a bit more flexibility on how data source can be retrieved.

What could be the next steps? You didn't close this PR straight away so there are still things that can be improved/removed.
- I can remove the POST request completely as it does not impact my use case that much
- I'm not in favor to remove the `custom header` feature as I need it to access restricted part of the remote API. However, I can change it into a input element to only accept ``authorization`` value
- Even though the two text areas are collapsible, it can be moved into a modal, reducing the number of inputs

What do you think?

**Comment by christabor** [comment]
Hey, sorry for the late reply. I'll look this through and post some notes soon. Thanks!

**Comment by christabor** [comment]
Ok, here's some of my feedback, I appreciate your patience.

> I can remove the POST request completely as it does not impact my use case that much

Makes sense to me - and of course you can always maintain your own branch as needed, and pull in upstream changes.

> I'm not in favor to remove the custom header feature as I need it to access restricted part of the remote API. However, I can change it into a input element to only accept authorization value

After some thought, I think custom headers is a useful case. My only concern is making it too "up-front. I think it could be well encapsulated in some kind of config  option for each module. My thinking is something along the lines of:

```json
{
    "modules": [
        {
            "type": "timeseries",
            "name": "my widget",
            "width": 400,
            "height": 400,
            "request": {
              "headers": {
                 "Content-Type": "application/json",
                 "Accept": "application/json",
                 "X-My-Header": "Something"
               }
            },
            "dataSource": "http://foo.bar,
            "order": 0
        }
    ]
}
```

where more of this type of data could live if it were to be expanded. I think the form itself probably should go elsewhere though, perhaps further down, with a smaller sized textarea. The reason being, I just don't see it being used a ton, and therefore it takes up a lot of real estate but may not be used. Making it collapsible is also good, I think that's probably the best approach at the moment. It looks like they are sort of indented in the screenshot - is this intentional? It makes sense if the goal is to encapsulate it as part of the `dataSource` config  - though if it was to use some kind of new "request" key/value list in the json, it might make more sense to put that as a single item in this new section (with the dropdown). I might be over-thinking it. Perhaps maybe nested as you have it, but under some new title, like

```
## Request options

* Headers [+]
* Option 2 [+]
```

Which when each is clicked, launched a bootstrap popover with the textarea? This is a bit of clicking, but seems the cleanest.

> Even though the two text areas are collapsible, it can be moved into a modal, reducing the number of inputs

I think switching the type of display for only one area of the form would be inconsistent and lead to a poorer user experience. To be honest the entire edit form modal needs to be rethought a bit more clearly, and allow more complex scenarios without getting in the way (possibly tabs), but for now I think it can remain the same.

**Comment by christabor** [comment]
Sounds good. I think this is a valuable change and look forward to it. I'll close this for now, but feel free to submit a new one.

**Pull request closed without merging**
